import { AnalysisResult } from '@/types/agent';

export function generatePDFReport(result: AnalysisResult): void {
  const content = `
================================================================================
                    AGENTIC AI DRUG REPURPOSING REPORT
================================================================================

Molecule: ${result.moleculeName.toUpperCase()}
Generated: ${new Date(result.timestamp).toLocaleString()}
Report ID: ${result.id}

--------------------------------------------------------------------------------
                              EXECUTIVE SUMMARY
--------------------------------------------------------------------------------

${result.synthesis.recommendation}

Confidence Score: ${(result.synthesis.confidenceScore * 100).toFixed(0)}%

--------------------------------------------------------------------------------
                              MARKET INSIGHTS
--------------------------------------------------------------------------------

Market Size: ${result.market.marketSize}
CAGR: ${result.market.cagr}

Leading Competitors:
${result.market.leadingCompetitors.map(c => `  • ${c}`).join('\n')}

Summary: ${result.market.summary}

Growth Drivers:
${result.market.growthDrivers.map(d => `  • ${d}`).join('\n')}

--------------------------------------------------------------------------------
                            CLINICAL TRIALS
--------------------------------------------------------------------------------

Total Active Trials: ${result.clinical.totalTrials}

Trial Distribution by Phase:
${result.clinical.phases.map(p => `  • ${p.phase}: ${p.count} trials`).join('\n')}

Key Sponsors:
${result.clinical.sponsors.map(s => `  • ${s}`).join('\n')}

Clinical Insights: ${result.clinical.insights}

Target Indications:
${result.clinical.indications.map(i => `  • ${i}`).join('\n')}

--------------------------------------------------------------------------------
                           PATENT LANDSCAPE
--------------------------------------------------------------------------------

Total Patents: ${result.patent.totalPatents}
Key Expiry Years: ${result.patent.expiryYears.join(', ')}

Patent Holders:
${result.patent.holders.map(h => `  • ${h}`).join('\n')}

FTO Status: ${result.patent.ftoStatus}

Notes: ${result.patent.notes}

--------------------------------------------------------------------------------
                        RESEARCH & PUBLICATIONS
--------------------------------------------------------------------------------

Total Publications: ${result.research.publicationsCount}
Overall Sentiment: ${result.research.sentiment}

Recent Key Publications:
${result.research.publications.map(p => `  • "${p.title}" (${p.year}) - ${p.journal}`).join('\n')}

Key Research Findings:
${result.research.keyFindings.map(f => `  • ${f}`).join('\n')}

--------------------------------------------------------------------------------
                         KEY OPPORTUNITIES
--------------------------------------------------------------------------------

${result.synthesis.keyOpportunities.map((o, i) => `${i + 1}. ${o}`).join('\n')}

--------------------------------------------------------------------------------
                              RISK FACTORS
--------------------------------------------------------------------------------

${result.synthesis.risks.map((r, i) => `${i + 1}. ${r}`).join('\n')}

--------------------------------------------------------------------------------
                         RECOMMENDED NEXT STEPS
--------------------------------------------------------------------------------

${result.synthesis.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

================================================================================

                      Generated by Agentic AI Assistant
                    Drug Repurposing Intelligence Platform
                    
           This report is for informational purposes only and should
           not be considered as medical or investment advice.

================================================================================
  `.trim();

  // Create and download the file
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${result.moleculeName.replace(/\s+/g, '_')}_Repurposing_Report_${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
